[package]
name = "amux"
version = "0.4.0"
edition = "2021"
rust-version = "1.84"
resolver = "3"
description = "A terminal multiplexer"
license = "MIT"
repository = "https://github.com/blendonl/amux"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.5.61", features = ["derive", "env"] }
crossterm = "0.29.0"
getrandom = "0.3.4"
hmac = "0.12.1"
if-addrs = "0.15.0"
mdns-sd = { version = "0.21.4", default-features = false, features = ["async"] }
mlua = { version = "0.11.5", features = ["lua54", "vendored", "serialize", "anyhow"] }
nix = { version = "0.31.3", features = ["hostname", "process", "signal", "user"] }
portable-pty = "0.9.0"
postcard = { version = "1.1.3", features = ["use-std"] }
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_path_to_error = "0.1.20"
sha2 = "0.10.9"
shell-words = "1.1.1"
snow = "=0.9.6"
spake2 = "0.4.0"
tempfile = "3.27.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "signal", "time", "process", "io-std"] }
toml = "1.0.7"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
unicode-width = "0.2.2"
vt100 = "0.16.2"

[profile.dist]
inherits = "release"
lto = "thin"
strip = true
